/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fact.h"

int *
fact_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	printf("factorial_of_number(%d) is called\n",argp->a);
	int temp=argp->a;
	int f=1;
	while(temp>0)
	{
		f=f*temp;
		temp--;
	}
	result=f;

	return &result;
}
