/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "greater.h"


void
greater_prog_1(char *host,int x,int y,int z)
{
	CLIENT *clnt;
	int  *result_1;
	numbers  greater_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, GREATER_PROG, GREATER_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	greater_1_arg.a=x;
	greater_1_arg.b=y;
	greater_1_arg.c=z;
	result_1 = greater_1(&greater_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("Result:%d\n",*result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 5) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	greater_prog_1 (host,atoi(argv[2]),atoi(argv[3]),atoi(argv[4]));
exit (0);
}
