/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rev.h"

int *
rev_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	printf("reverse_of_number(%d) is called\n",argp->a);
	int temp=argp->a;
	int revv=0;
	int d;
	while(temp>0)
	{
		d=temp%10;
		revv=revv*10+d;
		temp=temp/10;
	}
	result=revv;

	return &result;
}
