/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "sum.h"

int *
sum_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	printf("sum_of_digits(%d) is called\n",argp->a);
	int temp=argp->a;
	int summ=0;
	int d;
	while(temp>0)
	{
		d=temp%10;
		summ=summ+d;
		temp=temp/10;
	}
	result=summ;
	return &result;
}
